volumes:
  data:
  zookeeper-data:

networks:
  fin-processor-net:

services:
  fin-processor-zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: fin-processor-zookeeper
    hostname: fin_processor_zookeeper
    restart: "no"
    networks:
      fin-processor-net:
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181

  fin-processor-kafka:
    image: confluentinc/cp-kafka
    container_name: fin-processor-kafka
    hostname: fin_processor_kafka
    restart: "no"
    networks:
      fin-processor-net:
    ports:
      - "9092:9092"
    depends_on:
      - fin-processor-zookeeper
    volumes:
      - data:/var/lib/kafka/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: fin_processor_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://fin_processor_kafka:9091,EXTERNAL://192.168.105.6:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
