replicaCount: 2

image:
  repository: finance-processor
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fin-processor.fin-processor.svc.cluster.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 512m
    memory: 1024Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 50
  periodSeconds: 30
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 50
  periodSeconds: 30
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: [ ]

# Additional volumeMounts on the output Deployment definition.
volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }
