name: Build

on:
  workflow_dispatch:
    inputs:
      app-version-override:
        description: "Manually specified app version. Example: 2024.03.0-SNAPSHOT"
        required: false
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - docker
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - README.md
      - docker
  pull_request_target:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - README.md
      - docker

env:
  JAVA_VERSION: 21

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0

      - name: Set app version
        run: |
          if [ -n "${{ inputs.app-version-override }}" ]; then
            APP_VERSION="${{ inputs.app-version-override }}"
          else
            APP_VERSION="2024.03.${{ github.run_id }}-SNAPSHOT"
          fi
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build project
        run: ./gradlew clean build

      - name: Build Docker image
        shell: bash
        run: docker build --build-arg APP_VERSION=${{ env.APP_VERSION }} -t finance-processor:latest .
